// <auto-generated />
namespace BP.Logger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class entityUpdate01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(entityUpdate01));
        
        string IMigrationMetadata.Id
        {
            get { return "201704251650123_entityUpdate01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
